
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2018-12-05T13:15:07+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f0e18c19163923a3c1d5aa5eb197553f52df582d",
 "version": "2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
